### ISSUE TITLE
modal header is left aligned

### ISSUE THREAD

**Issue by coda-apps** [SahraCompany/Bootstrap-4.x-RTL#4]
Hi

i did as you suggested here
and have found an issue - the h3 of the modal header is still left aligned - where it should be right aligned.

pls see sample here: https://jsfiddle.net/kneidels/aq9Laaew/303853/

any idea what needs to be fixed?

Thanks

**Comment by meghdad0072000** [comment]
@coda-apps 

.modal-header .close {
    padding: 1rem 1rem;
    ~~margin: -1rem auto -1rem -1rem;~~
}

.modal-header .close {
    padding: 1rem 1rem;
    margin: -1rem -1rem -1rem auto;
}
